version: 2
updates:
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: daily
    time: "00:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: Microsoft.AspNetCore.WebUtilities
    versions:
    - "> 1.1.2"
  - dependency-name: Microsoft.Build.Tasks.Core
    versions:
    - "> 14.3"
